# Generated by Django 5.0.6 on 2024-06-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_firstname', models.CharField(max_length=100)),
                ('employee_lastname', models.CharField(max_length=100)),
                ('employee_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('employee_email', models.CharField(max_length=100)),
                ('employee_phone', models.CharField(max_length=100)),
                ('employee_password', models.CharField(max_length=100)),
                ('employee_hire_date', models.DateField()),
                ('employee_position', models.CharField(max_length=100)),
                ('employee_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdminApp.departmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='EmpAttendanceModel',
            fields=[
                ('empattendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_in', models.DateTimeField()),
                ('sign_out', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employeemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveModel',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employeemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryModel',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_days', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employeemodel')),
            ],
        ),
    ]
