# Generated by Django 5.0.6 on 2024-06-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminApp', '0001_initial'),
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProjectModel',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', models.TextField()),
                ('project_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantModel',
            fields=[
                ('applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_firstname', models.CharField(max_length=100)),
                ('applicant_lastname', models.CharField(max_length=100)),
                ('applicant_email', models.CharField(max_length=100)),
                ('applicant_phone', models.CharField(max_length=100)),
                ('applicant_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HrModel',
            fields=[
                ('hr_id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_firstname', models.CharField(max_length=100)),
                ('hr_lastname', models.CharField(max_length=100)),
                ('hr_email', models.CharField(max_length=100)),
                ('hr_phone', models.CharField(max_length=100)),
                ('hr_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerModel',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('trainer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationModel',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.applicantmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerModel',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_first_name', models.CharField(max_length=100)),
                ('manager_last_name', models.CharField(max_length=100)),
                ('manager_email', models.CharField(max_length=100)),
                ('manager_phoneno', models.CharField(max_length=100)),
                ('manager_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.departmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceModel',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comments', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.jobapplicationmodel')),
                ('hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.hrmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignModel',
            fields=[
                ('project_assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('manager_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.managermodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.addprojectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentModel',
            fields=[
                ('recruitment_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.managermodel')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.recruitmentmodel'),
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_desc', models.TextField()),
                ('total_days', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.addprojectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignModel',
            fields=[
                ('taskassign_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.employeemodel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.taskmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.trainermodel')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAttendanceModel',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.jobapplicationmodel')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.trainingmodel')),
            ],
        ),
    ]
