# Generated by Django 5.0.6 on 2024-06-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addprojectmodel',
            name='project_days',
        ),
        migrations.AddField(
            model_name='addprojectmodel',
            name='project_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='addprojectmodel',
            name='project_start_date',
            field=models.DateField(null=True),
        ),
    ]
