# Generated by Django 5.0.6 on 2024-07-06 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
        ('ManagerApp', '0003_remove_projectassignmodel_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProjectModel',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', models.TextField()),
                ('project_start_date', models.DateField(null=True)),
                ('project_end_date', models.DateField(null=True)),
                ('project_status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold')], max_length=20)),
                ('priority_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('assigned_employees', models.ManyToManyField(related_name='assigned_projects', to='EmployeeApp.employeemodel')),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagerApp.managermodel')),
            ],
        ),
    ]
